openapi: 3.0.4
info:
  title: Lottery Numbers
  description: Lottery Numbers is a simple tool for looking up winning lottery numbers. It returns the winning lottery numbers based on the lottery name provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/lottery:
    get:
      summary: Lookup Winning Mega Millions Numbers
      description: Lottery Numbers is a simple tool for looking up winning lottery numbers. It returns the winning lottery numbers based on the lottery name provided.
      operationId: lottery
      parameters:
      - name: numbers
        in: query
        schema:
          type: string
        required: true
        description: The name of the lottery to lookup the winning numbers (e.g., powerball or megamillions)
        example: megamillions
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  drawDate: 2025-11-11
                  jackpot: $900 Million
                  numbers:
                  - 10
                  - 13
                  - 40
                  - 42
                  - 46
                  - 1
                  lotteryType: megamillions
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
